nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: "${FA_TOKEN}"
    npmRegistryServer: "https://npm.fontawesome.com/"

packageExtensions:
  eslint-config-airbnb-typescript@*:
    dependencies:
      eslint: "*"
      eslint-plugin-import: "*"
      eslint-plugin-jsx-a11y: "*"
      eslint-plugin-react: "*"
      eslint-plugin-react-hooks: "*"
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.0.0.cjs
