- label: Software
  id: software
  items:
    - screen-recording
    - figma

- label: Color
  id: color
  items:
    - color-blindness
    - generating-color-schemes

- label: Typography
  id: typography
  items:
    - fonts-and-copyright
    - choosing-fonts

- label: Project Planning
  id: project-planning
  items:
    - flowcharts

- label: Layout
  id: layout
  items:
    - gestalt-theory

- label: Design Elements
  id: design-elements
  items:
    - app-icons
    - icons-for-navigation
    - forms

- label: Interaction
  id: interaction
  items:
    - animation
